---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "[%(asctime)s] %(levelname)-8s %(message)s"

handlers:
    console:
        class: adda.util.TqdmHandler
        level: INFO
        formatter: simple

    file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        encoding: utf8

root:
    level: INFO
    handlers: [console, file_handler]

